[Settings]

[build]
  command = "npm run build:app"
  publish = "dist/apps/island-explorer"

[build.environment]
  NODE_VERSION = "20"

[[edge_functions]]
  function = "add-og-tags"
  path = "/route/*"

[[redirects]]
  from = "/api/*"
  to = "https://islandexplorertracker.availtec.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
