[Settings]

[build]
  command = "yarn build:sw:prod && yarn build"
  publish = "dist/apps/island-explorer"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/api/InfoPoint/rest/Vehicles/GetAllVehiclesForRoutes/*"
  to = "https://island-explorer-bus-server.netlify.app/api/InfoPoint/rest/Vehicles/GetAllVehiclesForRoutes/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "http://islandexplorertracker.availtec.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "http://localhost:4200"
